# These are supported funding model platforms

github: sealad886
buy_me_a_coffee: sealad886
# open_collective: username
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name
# custom: ['https://www.example.com', 'https://www.example2.com']
